### ISSUE TITLE
Doubt regarding answer_char_ranges !

### ISSUE THREAD

**Issue by prathusha94** [Maluuba/newsqa#25]
I am trying to merge the key "answer_char_ranges" from "combined-newsqa-data-v1.csv" into dev, train and test.csv based on the story id ! But I notice that in the file "combined-newsqa-data-v1.csv" each story id is occurring multiple times and has a different value for the key "answer_char_ranges" for every occurrence ! Is there any significant reason behind this ? Would there be problems with results if I pick just one of the values and use the files for this [code](https://github.com/davidgolub/QuestionGeneration) ?

Thank You !

**Comment by juharris** [comment]
The `answer_char_ranges` depend on the `story_text` and `question`.  There is more information [here](https://github.com/Maluuba/newsqa#csv).  So you see the same `story_id` multiple times because there are several questions per story (usually about 9) each with different answers.

I'm not sure exactly what you mean by picking just one of the values so I'll answer both possible questions:
* You should not just use the same `answer_char_ranges` for every occurrence of the same `story_id` because each occurrence has a different question.
* You should not just use only one of the values inside `answer_char_ranges` you should use the consensus one. The docs describe what the values mean: https://github.com/Maluuba/newsqa#csv. I'd recommend using the JSON version of the dataset because it simplifies a lot of this by showing a consensus answer: https://github.com/Maluuba/newsqa#json

You can find some other stats about the dataset [here](https://datasets.maluuba.com/NewsQA/stats).
