### ISSUE TITLE
Official scoring scripts

### ISSUE THREAD

**Issue by dirkweissenborn** [Maluuba/newsqa#8]
It would be good to have official scoring scripts for different settings, e.g. with or without "None" answers. It should also help to avoid differences in evaluations that might arise when using, for example, different tokenization.

**Comment by dirkweissenborn** [comment]
The current split dataset still contains "None" answers. Should they be ignored to be comparable to the results in the paper?

**Comment by juharris** [comment]
Actually, having "None" in the answers is fine. It's a good indicator to show that the answer isn't in the story.

When filtering in a certain section of the paper, we filtered out questions where ALL of the answers from each crowdsourcer were "None" which is what the splitting code now does.

For the experiments, we ignored "None" answers completely.

**Comment by xingdi-eric-yuan** [comment]
Hi @dirkweissenborn , in the paper we only used the samples that have answer for training and evaluating, because both Match-LSTM and BARB models use pointer style decoder, which tries to point to a head and a tail position from the given document as predict answer, so this kind of decoder can't deal with "None" type question well. We leave that part to future work. Thanks.

**Comment by dirkweissenborn** [comment]
Hi @xingdi-eric-yuan, that's what I thought :)

Hi @juharris, having None answers is of course great, but having a scoring scripts would still be useful, since the F1 measure depends on the tokenization, that is employed.

**Comment by dirkweissenborn** [comment]
Ahh, I found that you actually use the SQuAD script for scoring. That's good enough.
